CREATE TABLE IF NOT EXISTS members (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    member_number VARCHAR(50) UNIQUE,
    business_name VARCHAR(255),
    trade_name VARCHAR(255),
    legal_form VARCHAR(100),
    tax_id VARCHAR(50),
    description TEXT,
    main_segment VARCHAR(100),
    member_type VARCHAR(100),
    payment_method VARCHAR(100),
    payment_frequency VARCHAR(50),
    monthly_fee DECIMAL(10, 2),
    fee_up_to_date BOOLEAN DEFAULT FALSE,
    street VARCHAR(255),
    street_number VARCHAR(20),
    address_notes TEXT,
    apartment VARCHAR(50),
    city VARCHAR(100),
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    national_id VARCHAR(50),
    mobile_phone VARCHAR(50),
    phone VARCHAR(50),
    email VARCHAR(255),
    cpy_client BOOLEAN DEFAULT FALSE,
    piedras_day_member BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
